# Generated by Django 4.0.2 on 2022-02-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Face_recognition', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
